"""
MeridianAlgo Signals Module

Comprehensive technical indicators and signal generation for trading strategies.
"""

from .evaluation import SignalEvaluator
from .generator import SignalGenerator, TechnicalAnalyzer
from .indicators import (  # Trend Indicators; Momentum Indicators; Volatility Indicators; Volume Indicators; Support/Resistance

    ADX,
    ALMA,
    ATR,
    CCI,
    ChopinessIndex,
    CoppockCurve,
    DEMA,
    EMA,
    FisherTransform,
    HMA,
    KAMA,
    MACD,
    MassIndex,
    MFI,
    OBV,
    ROC,
    RSI,
    SMA,
    TEMA,
    TSI,
    VortexIndicator,
    VWAP,
    WMA,
    AccumulationDistribution,
    Aroon,
    AverageTrueRange,
    BollingerBands,
    ChaikinMoneyFlow,
    DonchianChannels,
    EaseOfMovement,
    FibonacciExtension,
    FibonacciRetracement,
    ForceIndex,
    Ichimoku,
    KeltnerChannels,
    Momentum,
    ParabolicSAR,
    PivotPoints,
    StandardDeviation,
    Stochastic,
    Supertrend,
    UltimateOscillator,
    WilliamsR,
)

__all__ = [
    # Trend
    "SMA",
    "EMA",
    "WMA",
    "DEMA",
    "TEMA",
    "KAMA",
    "HMA",
    "ALMA",
    "MACD",
    "ADX",
    "Aroon",
    "ParabolicSAR",
    "Supertrend",
    "Ichimoku",
    # Momentum
    "RSI",
    "Stochastic",
    "WilliamsR",
    "CCI",
    "ROC",
    "Momentum",
    "MFI",
    "TSI",
    "UltimateOscillator",
    "FisherTransform",
    "CoppockCurve",
    # Volatility
    "BollingerBands",
    "ATR",
    "KeltnerChannels",
    "DonchianChannels",
    "StandardDeviation",
    "AverageTrueRange",
    "ChopinessIndex",
    # Volume
    "OBV",
    "VWAP",
    "ChaikinMoneyFlow",
    "AccumulationDistribution",
    "ForceIndex",
    "EaseOfMovement",
    "VortexIndicator",
    "MassIndex",
    # S/R
    "PivotPoints",
    "FibonacciRetracement",
    "FibonacciExtension",
    # Generators/Evaluation
    "SignalGenerator",
    "TechnicalAnalyzer",
    "SignalEvaluator",
]

